# Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

## Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [1]:
import numpy as np

a = np.zeros((3,3))   # Create an array of all zeros
print(a)              


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [2]:

b = np.ones((3,3))    # Create an array of all ones
print(b)              


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [3]:

c = np.full((3,3), 2)  # Create a constant array
print(c)               


[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [4]:

d = np.eye(3)         # Create a 2x2 identity matrix
print(d)              


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:

e = np.random.random((3,3))  # Create an array filled with random values
print(e)                   

[[0.00268268 0.25531019 0.00638633]
 [0.10258479 0.78479715 0.61621527]
 [0.09358856 0.21277667 0.19002384]]


## Array indexing

A **slice** of an array is a view into the same data, so modifying it
will modify the original array.

In [6]:
a = np.eye(3,3)

print('a = \n',a)

a[0:2,0] = 2

print('a = \n',a)

b = a[0:2,0]

print('b = \n',b)

b[:1] = 3

print('a = \n',a)

a = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
a = 
 [[2. 0. 0.]
 [2. 1. 0.]
 [0. 0. 1.]]
b = 
 [2. 2.]
a = 
 [[3. 0. 0.]
 [2. 1. 0.]
 [0. 0. 1.]]


**Integer array indexing** allows you to construct arbitrary arrays using the data from another array.

In [7]:
a = np.eye(3,3)

print('a = \n',a)

a[0:2,0] = 2

print('a = \n',a)

b = a[[0,1],[0]]

print('b = \n',b)

b[:1] = 3

print('a = \n',a)

a = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
a = 
 [[2. 0. 0.]
 [2. 1. 0.]
 [0. 0. 1.]]
b = 
 [2. 2.]
a = 
 [[2. 0. 0.]
 [2. 1. 0.]
 [0. 0. 1.]]


**Boolean** array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition

In [27]:
a = np.random.random((3,4))

print(a)

mask = a>0.5

print('\n',a[mask])

[[0.38455792 0.50529156 0.75617962 0.64084549]
 [0.03605964 0.3054136  0.98752728 0.0881511 ]
 [0.76571043 0.7614409  0.87885683 0.06726093]]

 [0.50529156 0.75617962 0.64084549 0.98752728 0.76571043 0.7614409
 0.87885683]


In [28]:
print('Mean: ', a.mean())

print('Mean: ', a.mean(axis=1))

print('Min: ', a.min())

print('Min: ', a.min(axis=1))

print('Max: ', a.max())

print('Max: ', a.max(axis=1))

print('Standard deviation: ', a.std())

print('Standard deviation: ', a.std(axis=1))

Mean:  0.5147746074558661
Mean:  [0.57171865 0.3542879  0.61831727]
Min:  0.03605964184059163
Min:  [0.38455792 0.03605964 0.06726093]
Max:  0.987527279395928
Max:  [0.75617962 0.98752728 0.87885683]
Standard deviation:  0.31968170792940404
Standard deviation:  [0.13986249 0.37930161 0.3216182 ]


In [33]:
# array manipulation

print(a.transpose())

print('\n', a.transpose().shape)

print('\n', a.reshape(2,6))

print('\n',a.ravel())



[[0.38455792 0.03605964 0.76571043]
 [0.50529156 0.3054136  0.7614409 ]
 [0.75617962 0.98752728 0.87885683]
 [0.64084549 0.0881511  0.06726093]]

 (4, 3)

 [[0.38455792 0.50529156 0.75617962 0.64084549 0.03605964 0.3054136 ]
 [0.98752728 0.0881511  0.76571043 0.7614409  0.87885683 0.06726093]]

 [0.38455792 0.50529156 0.75617962 0.64084549 0.03605964 0.3054136
 0.98752728 0.0881511  0.76571043 0.7614409  0.87885683 0.06726093]


In [19]:
#Array From Numerical Ranges

x = np.arange(2,8,0.5) 
print(x)


x = np.linspace(10,20, 5, endpoint = True) 
print(x)

x = np.linspace(10,20, 5, endpoint = False) 
print(x)


[2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5]
[10.  12.5 15.  17.5 20. ]
[10. 12. 14. 16. 18.]


In [42]:
# mathematical functions

a = np.arange(9, dtype = np.float_).reshape(3,3) 

print('First array:') 
print(a) 
print('\n')  

print('Second array:') 
b = np.array([10,20,30]) 
print(b)
print('\n')  

print('Add the two arrays:') 
print(np.add(a,b)) 
print('\n')  

print('Add the two arrays:') 
print(a+b) 
print('\n')  

First array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Second array:
[10 20 30]


Add the two arrays:
[[10. 21. 32.]
 [13. 24. 35.]
 [16. 27. 38.]]


Add the two arrays:
[[10. 21. 32.]
 [13. 24. 35.]
 [16. 27. 38.]]




In [45]:
# concatenation

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

print(np.concatenate((a, b), axis=0))

print('\n', np.vstack((a, b)))


print('\n', np.concatenate((a, b.T), axis=1))

print('\n', np.hstack((a, b.T)))

print('\n', np.concatenate((a, b), axis=None))


[[1 2]
 [3 4]
 [5 6]]

 [[1 2]
 [3 4]
 [5 6]]

 [[1 2 5]
 [3 4 6]]

 [[1 2 5]
 [3 4 6]]

 [1 2 3 4 5 6]
